// "use client";
import { ReactLenis, useLenis } from "@studio-freight/react-lenis";
import type { Metadata } from "next";
import { Inter, Signika } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const signika = Signika({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const lenis = useLenis(({ scroll }) => {
  //   // called every scroll
  // });
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReactLenis root> */}
        {children}
        {/* </ReactLenis> */}
        <Footer />
      </body>
    </html>
  );
}
